#!/bin/bash
infile=$1
oaid=${infile%.png}
o=tile_${oaid#tileset_}

convert -crop 40x40+0+0  	$infile	${o}_sbd.png
convert -crop 40x40+40+0  	$infile	${o}_cbd.png
convert -crop 40x40+80+0 	$infile ${o}_nbd.png
convert -crop 40x40+120+0 	$infile	${o}_ntd.png
convert -crop 40x40+0+40        $infile ${o}_smd.png
convert -crop 40x40+40+40       $infile ${o}_cmd.png
convert -crop 40x40+80+40       $infile ${o}_nmd.png
convert -crop 40x40+120+40      $infile ${o}_std.png

