#!/bin/bash
infile=$1
oaid=${infile%.png}
o=tile_${oaid#tileset_}

convert -crop 40x40+0+0  	$infile	${o}_nw.png
convert -crop 40x40+40+0  	$infile	${o}_n.png
convert -crop 40x40+80+0 	$infile ${o}_ne.png
convert -crop 40x40+120+0 	$infile	${o}_nwi.png
convert -crop 40x40+160+0  	$infile ${o}_nei.png
convert -crop 40x40+0+40        $infile ${o}_w.png
convert -crop 40x40+40+40       $infile ${o}_c.png
convert -crop 40x40+80+40       $infile ${o}_e.png
convert -crop 40x40+120+40      $infile ${o}_swi.png
convert -crop 40x40+160+40      $infile ${o}_sei.png
convert -crop 40x40+0+80        $infile ${o}_sw.png
convert -crop 40x40+40+80       $infile ${o}_s.png
convert -crop 40x40+80+80       $infile ${o}_se.png
convert -crop 40x40+120+80      $infile ${o}_ci.png

