FIND_PATH(FFI_INCLUDE_DIR ffi.h /usr/include /usr/local/include /opt/include)

FIND_LIBRARY(FFI_LIBRARY NAMES ffi PATH /usr/lib /usr/local/lib /opt/lib) 

IF(FFI_INCLUDE_DIR AND FFI_LIBRARY)
   SET(FFI_FOUND TRUE)
ENDIF(FFI_INCLUDE_DIR AND FFI_LIBRARY)

IF (FFI_FOUND)
   IF (NOT Ffi_FIND_QUIETLY)
      MESSAGE(STATUS "Found FFI: ${FFI_LIBRARY}")
   ENDIF (NOT Ffi_FIND_QUIETLY)
ELSE(FFI_FOUND)
   IF(Ffi_FIND_REQUIRED)
      MESSAGE(FATAL_ERROR "Could not find FFI")
   ENDIF(Ffi_FIND_REQUIRED)
ENDIF(FFI_FOUND)
