#ifndef BXMLPARSER_PROTO_H
#define BXMLPARSER_PROTO_H
/*
This file was autogenerated from src/bxmlparser.c
by bin/genproto
Please do not hand edit.
*/

/** Struct to hold the state of the ragel parser. */
struct BXMLRagel_;
typedef struct BXMLRagel_ BXMLRagel;

