#ifndef BXML_PROTO_H
#define BXML_PROTO_H
/*
This file was autogenerated from src/bxml.c
by bin/genproto
Please do not hand edit.
*/

/**
* Kind of the self. Can be : ATTR, TEXT, TAG, 
* Comments, entities and parsing instructions are ignored for now
*/
enum BXMLKind_;
typedef enum BXMLKind_ BXMLKind;

;

/**
* Results of a parse
*/
enum BXMLResult_;
typedef enum BXMLResult_ BXMLResult;

;

/**
* An BXML represents one <tag></tag> self and it's children and attributes,
* or the attributes of a tag.
*/
struct BXML_;
typedef struct BXML_ BXML;

;

/**
* BXMLParser is the parser interface.
*/ 
struct BXMLParser_;
typedef struct BXMLParser_ BXMLParser;

/**
* BXMLParse is the parser object.
*/
struct BXMLParse_;
typedef struct BXMLParse_ BXMLParse;

;

/** Allocates a new bxml node */
BXML * bxml_alloc();

/** Allocates and initialzes a new bxml node. */
BXML * bxml_new(int kind, BXML * parent);

/** Clean usp a bxml  node, freeing the children recursively. */
BXML * bxml_done(BXML * self);

/** Frees this node and cleans up its children recursively. returns NULL. */
BXML * bxml_free(BXML * self);

#endif // BXML_PROTO_H

