#ifndef CH_PROTO_H
#define CH_PROTO_H
/*
This file was autogenerated from src/ch.c
by bin/genproto
Please do not hand edit.
*/

/** Chipmunk helper functions. */
#include <stdlib.h>
#include <string.h>
#include <lauxlib.h>
#include "ch.h"

/** Allocates a rectangular box shape, with the given width and height
*   and offsets from center.
*/
cpPolyShape *
chBoxOffsetInit(cpPolyShape *poly, cpBody *body,
                cpFloat w, cpFloat h, cpFloat xoff, cpFloat yoff)
;

#endif // CH_PROTO_H

