#ifndef DRAW_PROTO_H
#define DRAW_PROTO_H
/*
This file was autogenerated from src/draw.c
by bin/genproto
Please do not hand edit.
*/

/** Addinional drawing functions and wrappers for primitive drwaing 
functionality. */


/** Draws an image on the current target bitmap according to a 9 part scaling
algorithm. This splits the bitmap in 9 parts, keeps the 4 corners unscaled, but
scales the 4 edges and the center according to the desired size.
The 4 corners should be rectangles of identical size corner_w by corner_h in
the original image. Pass a nonpositive number to have the corner sizes automatically calculated.
new_w and new_h are the new dimensions the new image should have.
This is useful for GUI backgrounds.
*/
void image_blitscale9(Image * img, int xx, int yy,
                                  int new_w, int new_h,
                                  int corner_w, int corner_h);

/*** Draws a filled rectange at the given position with the given size */
void draw_slab(int x, int y, int w, int h, Color col);

/*** Draws a rounded filled rectange at the given position with the given size */
void draw_roundslab(int x, int y, int w, int h, int rx, int ry, Color col);

/*** Draws an open rectange at the given position with the given size */
void draw_box(int x, int y, int w, int h, Color col, int tt);

/** Draws a rounded rectangle at the given position with the given size */
void draw_roundbox(int x, int y, int w, int h, int rx, int ry, Color col, int tt);

/** Draws a filled frame of the given thickness on the active bitmap.
* The outer size of the frame will be ww and hh.
* border color is fg, background color is bg. */
void draw_frame(int xx, int yy, int ww, int hh, int tt, Color fg, Color bg);

/** Draws a filled, rounded frame of the given thickness on the active bitmap.
* The rounding is autocalulated. The outer size of the frame will be ww and hh.
* border color is fg, background color is bg.
*/
void draw_roundframe(int xx, int yy, int ww, int hh, int tt, Color fg, Color bg);

#endif // DRAW_PROTO_H

