#ifndef EVERY_H_INCLUDED
#define EVERY_H_INCLUDED

/**
* Every is an iterator that allows to iterate over every element of
* a collection.
*/

struct Every_;
typedef struct Every_ Every;

struct EveryActs_;
typedef struct EveryActs_ EveryActs;


// types for the funtion pointers that every uses
typedef Every * (EveryNext(Every * every));
typedef void  * (EveryPut(Every * every, void * element));
typedef void  * (EveryDone(Every * every));
typedef Every * (EveryInit(Every * every));

// Struct with all function pointers for Every
struct EveryActs_ {
  EveryDone * done;
  EveryInit * init;
  EveryNext * next;
  EveryPut  * put;
};

/**
* Every is a struct that can be used with collections like Dynar to fetch
* every element of the collection.
*/
struct Every_ {
  void         * now;
  void         * on;
  int            index;
  void         * extra;
  EveryActs    * acts;
};


struct Each_;
typedef struct Each_ Each;
/**
* Each is an alternative iterator interface, that
* requires a function callback in stead of an object. 
*/
struct Each_ {
  void * on;
  void * now;
  void * extra;
  int    index;
};

/** Function pointer for the each iteration method.  */
typedef void * (EachDo(Each * element));

// get autogenerated function prototypes.
#include "every_proto.h"

// and some helper macros
#define EACH_NOW(EACH, TYPE) ((TYPE *) each_now(EACH))



#endif
