#ifndef EVERY_PROTO_H
#define EVERY_PROTO_H
/*
This file was autogenerated from src/every.c
by bin/genproto on 2012-01-19 11:57:35 +0100
Please do not hand edit.
*/

/** Allocates an uninitialized every object. */
Every * every_alloc();

/** Deinitializes an every object.  */
Every * every_done(Every * self);

/** Frees an every object. */
Every * every_free(Every * self);

/** Initializes an every object. */
Every * every_init(Every * self, EveryActs * acts);

/** Creates a new every object. */
Every * every_new(EveryActs * acts);

/** Gets the current object pointed to by the Every object. */
void * every_get(Every * self);

/** Puts an object at the current position if possible.
* Returns NULL if the put failed.
*/
void * every_put(Every * self, void * data);

/** Moves on to the next object and returns it.
* Return NULL if no next object.
*/
Every * every_next(Every * self, void * data);

#endif // EVERY_PROTO_H

