#ifndef FLAGS_PROTO_H
#define FLAGS_PROTO_H
/*
This file was autogenerated from src/flags.c
by bin/genproto
Please do not hand edit.
*/

/** Simple bit twiddling functions for setting and getting 
flags (bits) on an integer field. */


/** Sets an individual flag on self. */
int flags_set(int * self, int flag);

/** Returns the new flag that self should be set to for 
flag to be set in self. */
int flags_setvalue(int self, int flag);

/** Unsets an individual flag on the widget. */
int flags_unset(int * self, int flag);

/** Returns the new flag that self should be set to for 
flag to be unset in self. */
int flags_unsetvalue(int self, int flag);

/** Sets or unsets an individual flag on the self. 
If set is true the flag is set, if false it's unset. */
int flags_put(int * self, int flag, int set);

/** Sets or unsets an individual flag on the self. 
If set is true the flag is set, if false it's unset. */
int flags_putvalue(int self, int flag, int set);

/** Checks if an individual flag is set. */
int flags_get(int self, int flag);

/** Checks if an individual flag is set. Pass in a pointer. */
int flags_getptr(int * self, int flag);

#endif // FLAGS_PROTO_H

