#ifndef FORLUA_PROTO_H
#define FORLUA_PROTO_H
/*
This file was autogenerated from src/forlua.c
by bin/genproto on 2012-01-23 14:50:46 +0100
Please do not hand edit.
*/

/** All functions have a fl prefix that stands for "Function for Lua" */


#ifdef COMMENT_



/** Initializes the map. */

int fl_mapinit(lua_State * lua);

/** Sets a single tile in the map. */
int fl_mapset(lua_State * lua);

/** Sets a row of tiles in the map. */
int fl_mapsetrow(lua_State * lua);

/** Fills a whole layer in the map. */
int fl_mapfill(lua_State * lua);

/** Sets tile info for the map. */
int fl_maptileinfo(lua_State * lua);

/** Walker that sets multiple tile infos from a hash to a map. */
int fl_maptiledata_walker(lua_State * lua, void * data);

/** Sets multiple tile infos from a hash to a map. */
int fl_maptiledata(lua_State * lua);

#endif // FORLUA_PROTO_H

