#ifndef GLH_PROTO_H
#define GLH_PROTO_H
/*
This file was autogenerated from src/glh.c
by bin/genproto
Please do not hand edit.
*/

/** OpenGL helper functions */
#include "glh.h"
#include "mem.h"


enum type;
typedef enum type typ;

#endif // GLH_PROTO_H

