#ifndef GLH_PROTO_H
#define GLH_PROTO_H
/*
This file was autogenerated from src/glh.c
by bin/genproto on 2012-01-24 10:26:30 +0100
Please do not hand edit.
*/

/** OpenGL helper functions */


GLuint glh_shader_make(GLenum type, char * data);

#endif // GLH_PROTO_H

