#ifndef MAIN_PROTO_H
#define MAIN_PROTO_H
/*
This file was autogenerated from src/main.c
by bin/genproto on 2012-01-19 11:57:35 +0100
Please do not hand edit.
*/

/** For some reason, onlt wav music plays?
It seems there is a bug in init_dynlib() in the ogg driver nbut only
if Allegro is compiled in the default RelWithDbg mode.
***/
#define ERUTA_TEST_MUSIC "data/music/musictest.ogg"


int main(void);

#endif // MAIN_PROTO_H

