#ifndef MAIN_PROTO_H
#define MAIN_PROTO_H
/*
This file was autogenerated from src/main.c
by bin/genproto on 2012-02-27 15:08:40 +0100
Please do not hand edit.
*/

/** For some reason, onlt wav music plays?
It seems there is a bug in init_dynlib() in the ogg driver nbut only
if Allegro is compiled in the default RelWithDbg mode.
***/
#define ERUTA_TEST_MUSIC "data/music/musictest.ogg"
#define ERUTA_MAP_TEST "data/map/map_0001.tmx"
#define RUN_TESTS

#ifdef RUN_TESTS

const char * xml_test_doc = 
"<?xml ?> "
"<!-- Comment should be ignored -->"
"<map high=\"100\" wide=\"200\">"
"<layer>"
"0,1,2,3\n"
"0,1,0,0\n"
"0,0,1,0\n"
"</layer>"
"</map>";

int test_xml(void);

#endif // MAIN_PROTO_H

