#ifndef MEM_PROTO_H
#define MEM_PROTO_H
/*
This file was autogenerated from src/mem.c
by bin/genproto on 2012-01-30 15:22:16 +0100
Please do not hand edit.
*/

/** Wrapper for calloc/malloc */
void * mem_calloc(size_t amount, size_t size);

/** Wrapper for calloc/malloc */
void * mem_alloc(size_t size);

/** Wrapper for free */
void * mem_free(void * ptr);

/** Wrapper for realloc */
void * mem_realloc(void *ptr, size_t newsize);

/** Resizes memory, taking care not to lose ptr* if the reallocation
fails. */
void * mem_resize(void ** ptr, size_t newsize);

/** Wrapper for memmove, for consistency */
void * mem_move(void * dest, void * src, size_t size);

#endif // MEM_PROTO_H

