#ifndef MOBILE_PROTO_H
#define MOBILE_PROTO_H
/*
This file was autogenerated from src/mobile.c
by bin/genproto on 2012-01-19 11:57:35 +0100
Please do not hand edit.
*/

/**
* A mobile is any visible object that can move around
* autonomously. 
*/


#endif // MOBILE_PROTO_H

