#ifndef MOBILE_PROTO_H
#define MOBILE_PROTO_H
/*
This file was autogenerated from src/mobile.c
by bin/genproto
Please do not hand edit.
*/

/**
* A mobile is any visible object that can move around
* autonomously. 
*/


#endif // MOBILE_PROTO_H

