#ifndef REACT_PROTO_H
#define REACT_PROTO_H
/*
This file was autogenerated from src/react.c
by bin/genproto
Please do not hand edit.
*/

/** Initializes the react structure so it does nothing at all in all cases. */
React * react_initempty(React * self, void * data);

/** React to an allegro event. */
React * react_react(React * self, ALLEGRO_EVENT * event);

/** Polls for allegro events and reacts to them. */
React * react_poll(React * self, void * state);

#endif // REACT_PROTO_H

