#ifndef RH_PROTO_H
#define RH_PROTO_H
/*
This file was autogenerated from src/rh.c
by bin/genproto
Please do not hand edit.
*/

/** Allocates and initialzes a new ruby state. */
Ruby * rh_new();

/** Frees a ruby state. */
Ruby * rh_free(Ruby * self);

/**
* Executes a ruby file in Eruta's data/script directory.
* Returns -2 if the file ws not found.
*/
int rh_dofile(Ruby * self, const char * filename);

#endif // RH_PROTO_H

