#ifndef STR_PROTO_H
#define STR_PROTO_H
/*
This file was autogenerated from src/str.c
by bin/genproto
Please do not hand edit.
*/

/** Converts an US string to a number as per atoi. */
int ustr_atoi(USTR * str);

/** Converts a ustr to s double by using strtod. Return 0 and sets OK to
NULL if conversion failed for some reason. If OK is NULL, it is ignored.  */
double ustr_tod(USTR * ustr, int * ok);

/** Converts a ustr to s double by using strtol. Return 0 and sets OK to
NULL if conversion failed for some reason. If OK is NULL, it is ignored.  */
long ustr_tol(USTR * ustr, int * ok, int base);

/** Converts an ustr to a double without doing any error checking. */
double ustr_atod(USTR * ustr);

/** Converts an ustr to a long without doing any error checking. 
    Uses the decimal base. 
*/
double ustr_atol(USTR * ustr);

/** Makes a new ustr from the double. Must be freed with ustr_free */
USTR * ustr_newdouble(double d);

/** Makes a new ustr from a long. Must be freed with ustr_free */
USTR * ustr_newlong(long l);

#endif // STR_PROTO_H

