#ifndef STR_PROTO_H
#define STR_PROTO_H
/*
This file was autogenerated from src/str.c
by bin/genproto on 2012-01-31 09:33:01 +0100
Please do not hand edit.
*/

/** Converts a STR string to a number as per atoi. */
int str_atoi(STR * str);

#endif // STR_PROTO_H

