#ifndef TILEIO_PROTO_H
#define TILEIO_PROTO_H
/*
This file was autogenerated from src/tileio.c
by bin/genproto
Please do not hand edit.
*/

/** Loads a single tile pane of the tile map from xml (tmx). */
Tilepane * tilemap_loadpanexml(Tilemap * map, xmlNode * xlayer, int count);

/** Loads the tile panes of the tile map from xml (tmx). */
Tilemap * tilemap_loadpanesxml(Tilemap * map, xmlNode * xlayer);

/** Loads a tile map from a tmx xml document
*/
Tilemap * tilemap_loadxml(xmlDoc * xml);

/**
* Loads a tile map from a tmx file.
*/
Tilemap * tilemap_loadtmx(const char * filename);

/**
* Loads a tile map.
*/
Tilemap * tilemap_load(char * filename);

#endif // TILEIO_PROTO_H

