#ifndef TILEIO_PROTO_H
#define TILEIO_PROTO_H
/*
This file was autogenerated from src/tileio.c
by bin/genproto
Please do not hand edit.
*/

/**
 * print_element_names:
 * @a_node: the initial xml node to consider.
 *
 * Prints the names of the all the xml elements
 * that are siblings or children of a given xml node.
 */
static void print_element_names(xmlNode * node);

/**
* Loads a tile map from a tmx file.
*/
Tilemap * tilemap_loadtmx(const char * filename);

/**
* Loads a tile map.
*/
Tilemap * tilemap_load(char * filename);

#endif // TILEIO_PROTO_H

