#ifndef TILEIO_PROTO_H
#define TILEIO_PROTO_H
/*
This file was autogenerated from src/tileio.c
by bin/genproto on 2012-01-30 15:48:22 +0100
Please do not hand edit.
*/

/**
* Loads a tile map from a tmx file.
*/
Tilemap * tilemap_loadtmx(FILE * fin);

/**
* Loads a tile map.
*/
Tilemap * tilemap_load(char * filename);

#endif // TILEIO_PROTO_H

