#ifndef TILEMAP_PROTO_H
#define TILEMAP_PROTO_H
/*
This file was autogenerated from src/tilemap.c
by bin/genproto on 2012-01-23 14:50:46 +0100
Please do not hand edit.
*/

/** A tile map is a game map that uses tiled layers for it's 
display and physics. */

struct Tilemap_;
typedef struct Tilemap_ Tilemap;

/** Loads an image of the given category and index as a texture. */
Image * image_loadtexture(const char * category, int index);

/** Cleans up a tilemap. */
Tilemap * tilemap_done(Tilemap * self);

/** Initializes a tile map */
Tilemap* tilemap_init(Tilemap * self, int textureid, int w, int h);

/** Returns a pointer to the pane at index or NULL if out of range. */
Tilepane * tilemap_layer(Tilemap * self, int layer);

/** Sets a tile in the tile map to the given tile. */
Tile * tilemap_settile(Tilemap * self, int l, int x, int y, Tile * tile);

/** Sets a tile in the tile map to the tile with the given index. */
Tile * tilemap_setindex(Tilemap * self, int l, int x, int y, int index);

/** Fills a rectangle in the  */
int tilemap_recttile(Tilemap * self, int l, int x, int y, int w, int h, int tile);

/** Sets tile info for given the map and tile. */
int tilemap_tileinfo_(Tilemap * self, int tile, int info);

/** Gets tile info for given the map and tile. */
int tilemap_tileinfo(Tilemap * self, int tile);

/** Checks if a tile index is a wall tile. */
int tilemap_tilewall(Tilemap * self, int tile);

/** Makees a physical wall in the chipmunk space of the map at the given 
tile coordinates. Returns the wall shape. */

cpShape * tilemap_makewall(Tilemap * self, int tx, int ty);

#endif // TILEMAP_PROTO_H

