#ifndef UI_PROTO_H
#define UI_PROTO_H
/*
This file was autogenerated from src/ui.c
by bin/genproto
Please do not hand edit.
*/

/** UI manages the graphical user interface and menus. */
struct UI_;
typedef struct UI_ UI;

/** Allocates an unitinialized UI. */
UI * ui_alloc();

/** Draws the user interface */


/** Initializes the user interface. */






#endif // UI_PROTO_H

