#ifndef XML_PROTO_H
#define XML_PROTO_H
/*
This file was autogenerated from src/xml.c
by bin/genproto on 2012-02-23 15:41:52 +0100
Please do not hand edit.
*/

/**
* Xml is both an XML node and an xml document.
*/
struct Xml_;
typedef struct Xml_ Xml;

/**
* Xmlparser is an XML parser.
*/
struct Xmlparser_;
typedef struct Xmlparser_ Xmlparser;

/** Allocates a new XML document, attribute or node. */
Xml * xml_new(STR * tag, STR * value);

/** Frees an XML document recursively */
Xml * xml_free(Xml * xml);

/** Deallocates an XML document recursively.
   Children, siblings and attributes will be freed.  */
Xml * xml_done(Xml * xml);

/** Adds a sibling to an existing xml node and returns it.
* It will scan through the sibling list and append it to the end. */
Xml * xml_addsibling(Xml * xml, Xml * sibling);

/** Adds a child to an existing xml node. */
Xml * xml_addchild(Xml * xml, Xml * child);  

/** Adds an attribute attr to an existing xml node. */
Xml * xml_addchild(Xml * xml, Xml * attr);

#endif // XML_PROTO_H

