#ifndef XMLPARSER_PROTO_H
#define XMLPARSER_PROTO_H
/*
This file was autogenerated from src/xmlparser.c
by bin/genproto on 2012-02-27 15:08:40 +0100
Please do not hand edit.
*/

#endif // XMLPARSER_PROTO_H

